name: Trading Bot Automation

on:
  schedule:
    - cron: "*/5 13-20 * 3-11 1-5"  # DST: March–November (EDT)
    - cron: "*/5 14-21 * 12,1,2 1-5"  # Standard Time: December–February (EST)
  workflow_dispatch:

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest

    env:
      ALPACA_API_KEY_1: ${{ secrets.ALPACA_API_KEY_1 }}
      ALPACA_SECRET_KEY_1: ${{ secrets.ALPACA_SECRET_KEY_1 }}
      ALPACA_API_KEY_2: ${{ secrets.ALPACA_API_KEY_2 }}
      ALPACA_SECRET_KEY_2: ${{ secrets.ALPACA_SECRET_KEY_2 }}

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run the Trading Bot
      - name: Execute Trading Bot
        run: |
          python trad1501.py
      - name: Debug Environment Variables
        run: |
          echo "ALPACA_API_KEY_1=${{ secrets.ALPACA_API_KEY_1 }}"
          echo "ALPACA_SECRET_KEY_1=${{ secrets.ALPACA_SECRET_KEY_1 }}"

      # 5️⃣ Upload Logs (Optional)
      - name: Upload Trade Logs
        uses: actions/upload-artifact@v3
        with:
          name: trade-logs
          path: trade_log.txt
